// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunDecrypt(arg1) {
  return window['go']['main']['App']['RunDecrypt'](arg1);
}

export function RunEncrypt(arg1) {
  return window['go']['main']['App']['RunEncrypt'](arg1);
}

export function SelectInputZip() {
  return window['go']['main']['App']['SelectInputZip']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SelectOutputZip() {
  return window['go']['main']['App']['SelectOutputZip']();
}

export function SelectSourceDir() {
  return window['go']['main']['App']['SelectSourceDir']();
}
