// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function RunDecrypt(arg1:main.DecryptConfig):Promise<main.DecryptResult>;

export function RunEncrypt(arg1:main.EncryptConfig):Promise<main.EncryptResult>;

export function SelectInputZip():Promise<string>;

export function SelectOutputDir():Promise<string>;

export function SelectOutputZip():Promise<string>;

export function SelectSourceDir():Promise<string>;
