// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function RunEncrypt(arg1:main.EncryptConfig):Promise<main.EncryptResult>;

export function SelectOutputZip():Promise<string>;

export function SelectSourceDir():Promise<string>;
