// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunEncrypt(arg1) {
  return window['go']['main']['App']['RunEncrypt'](arg1);
}

export function SelectOutputZip() {
  return window['go']['main']['App']['SelectOutputZip']();
}

export function SelectSourceDir() {
  return window['go']['main']['App']['SelectSourceDir']();
}
