// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function RunEncrypt(arg1:gui.EncryptConfig):Promise<gui.EncryptResult>;

export function RunRecover(arg1:gui.RecoverConfig):Promise<gui.RecoverResult>;

export function SelectInputZip():Promise<string>;

export function SelectOutputDir():Promise<string>;

export function SelectOutputZip():Promise<string>;

export function SelectSourceDir():Promise<string>;
