// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunEncrypt(arg1) {
  return window['go']['gui']['App']['RunEncrypt'](arg1);
}

export function RunRecover(arg1) {
  return window['go']['gui']['App']['RunRecover'](arg1);
}

export function SelectInputZip() {
  return window['go']['gui']['App']['SelectInputZip']();
}

export function SelectOutputDir() {
  return window['go']['gui']['App']['SelectOutputDir']();
}

export function SelectOutputZip() {
  return window['go']['gui']['App']['SelectOutputZip']();
}

export function SelectSourceDir() {
  return window['go']['gui']['App']['SelectSourceDir']();
}
